name: Kernel Upstream

on:
  workflow_dispatch:

jobs:
  upstream:
    name: Upstream Patch to 4.19
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Kernel Repository
        uses: actions/checkout@v3

      - name: Configure Git Identity
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Download and Apply Patches
        run: |
          for ver in $(seq -w 001 275); do
            PATCH_URL="https://cdn.kernel.org/pub/linux/kernel/v4.x/incr/patch-4.14.$ver.xz"
            PATCH_FILE="patch-4.14.$ver.xz"
            wget -q "$PATCH_URL" || break
            xz -d "$PATCH_FILE"
            patch -p1 < "patch-4.14.$ver" || break
          done

          for ver in $(seq -w 001 303); do
            PATCH_URL="https://cdn.kernel.org/pub/linux/kernel/v4.x/incr/patch-4.19.$ver.xz"
            PATCH_FILE="patch-4.19.$ver.xz"
            wget -q "$PATCH_URL" || break
            xz -d "$PATCH_FILE"
            patch -p1 < "patch-4.19.$ver" || break
          done

      - name: Show Diff
        run: git diff | tee patch.diff || echo "No diff"

      - name: Commit Changes
        run: |
          git add .
          git commit -m "Auto: Upstream patch to 4.19" || echo "No changes to commit"

      - name: Push Changes
        run: |
          git push || echo "Nothing to push"

      - name: Upload Patch Log
        uses: actions/upload-artifact@v3
        with:
          name: patch-diff-log
          path: patch.diff
